// <auto-generated />
using System;
using ContractorERP.Modules.WorkOrders.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContractorERP.Modules.WorkOrders.Infrastructure.Migrations
{
    [DbContext(typeof(WorkOrdersDbContext))]
    partial class WorkOrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("work_orders")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContractorERP.Modules.WorkOrders.Domain.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AssignmentDate")
                        .HasColumnType("date");

                    b.Property<string>("Basket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<decimal?>("PartialAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WorkTypeCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("WorkYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number", "WorkTypeCode")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "WorkYear", "DisplayOrder");

                    b.ToTable("work_orders", "work_orders", t =>
                        {
                            t.HasCheckConstraint("ck_work_orders_partial", "\"PartialAmount\" IS NULL OR (\"PartialAmount\" > 0 AND \"PartialAmount\" <= \"Value\")");

                            t.HasCheckConstraint("ck_work_orders_value", "\"Value\" >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
